### ISSUE TITLE
Timestamps in NTP format

### ISSUE THREAD

**Issue by melhousni** [xioTechnologies/NGIMU-Software-Public#2]
Hi, is it possible to get the timestamps for each measurement in NTP format rather than from when the logging started ?

**Comment by xioTechnologies** [comment]
The data logger provides all logged data data in a single Session directory.  The sessions directory contains a device directory for each NGIMU.  If you are only using one NGIMU then there will only be one device directory.  The device directory contains all the CSV files for the logged data for that device.  The device directory also contains the metadata file: Device.xml file.  This file contains the date and time of the first timestamp received for that device.

The timestamps in each CSV are the number of seconds since the first timestamp received from any device.

It is possible to calculate the date/time of each timestamp in each CSV file using the the information described above.

Perhaps you do not need the timestamp of each sample to be a date/time and knowing the first timestamp available in the Device.xml file is sufficient.  If you do need the timestamp of each sample to be a date/time then please can you explain why and we will consider if this feature should be introduced to the software.

**Comment by melhousni** [comment]
I am trying to find a way to synchronize the NGIMU with an external camera since they don't have the same clock, which led me to think that maybe if they both timestamps there data in NTP format they could somewhat have a common "clock" ...
However I doubt this will work... Any suggestion on how I could achieve this synchronization ?
